version: '3'

networks:
  blockchain-bitcoin-net:
    external: true

services:

  ####
  #### BUILD: docker-compose build cloudbeaver-frontend
  #### VERIFY: docker run -ti marcellodesales/cloudbeaver-frontend find /dbeaver/cloud/frontend -name "@cloudbeaver"
  ####
  cloudbeaver:
    image: ghcr.io/marcellodesales/cloudbeaver:master-7258fc8
    container_name: cloudbeaver-server
    labels:
      com.github.marcellodesales.type: runtime
    networks:
      - blockchain-bitcoin-net
    ports:
      - 8978:8978
    volumes:
      - ./tools/cloudbeaver/data/logs:/opt/cloudbeaver/logs
      - ./tools/cloudbeaver/workspace:/opt/cloudbeaver/workspace

    # https://medium.com/geekculture/how-to-successfully-implement-a-healthcheck-in-docker-compose-efced60bc08e
    healthcheck:
      # docker exec -ti postgrest-api which wget ---> /usr/bin/wget, the internal port within the container
      test: wget --no-verbose --tries=1 --spider http://localhost:8978 || exit 1
      interval: 30s
      timeout: 5s
      retries: 5

  postgrest-api:
    image: swaggerapi/swagger-ui:v4.10.3
    container_name: postgrest-api
    ports:
      - "4566:8080"
    environment:
      # The API docs page from the postgrest. This would be usually from /api/docs path
      API_URL: http://localhost:4565/

    # https://medium.com/geekculture/how-to-successfully-implement-a-healthcheck-in-docker-compose-efced60bc08e
    healthcheck:
      # https://serverfault.com/questions/919036/return-only-a-http-status-code-from-curl-command/919042#919042
      test: curl -s -o /dev/null -w "%{http_code}" -I --fail -sS http://localhost:8080 || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
